"""Create DB

Revision ID: 86935a7703e3
Revises: 
Create Date: 2024-08-14 19:01:58.472736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86935a7703e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WebHistory_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_event', sa.String(), nullable=False),
    sa.Column('path_img', sa.LargeBinary(), nullable=False),
    sa.Column('path_img_map', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebHistory_directionlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_direction_line', sa.String(), nullable=False),
    sa.Column('path_img_line', sa.LargeBinary(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['WebHistory_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebHistory_sideboundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_side_boundaries', sa.String(), nullable=False),
    sa.Column('path_img_boundaries', sa.LargeBinary(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['WebHistory_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebHistory_sideboundaries')
    op.drop_table('WebHistory_directionlines')
    op.drop_table('WebHistory_event')
    # ### end Alembic commands ###
